services:
  app:
    # image: monashfit/fit3143
    build: .
    ports:
      - 2222:22
    hostname: fit3143
    volumes:
      - .:/home/student/project:rw
      # - ./ssh/authorized_keys:/home/student/.ssh/authorized_keys
