services:
  app:
    # image: monashfit/fit3143
    build: .
    ports:
      - 2222:22
    hostname: fit3143
    volumes:
      - .:/home/student/project:rw
      # - ./ssh/authorized_keys:/home/student/.ssh/authorized_keys

  launcher:
    build: .
    network_mode: host
    user: student
    command: ["sleep", "infinity"]
    volumes:
      - .:/home/student/project:rw
      - ${HOME}/.ssh/id_ed25519:/home/student/.ssh/id_ed25519:ro
      - ${HOME}/.ssh/config:/home/student/.ssh/config:ro
